### ISSUE TITLE
toggleToolbox('all','off') also disables non-Toolbox functions in R2017a

### ISSUE THREAD

**Issue by zhuowei** [rodyo/FEX-toggleToolbox#1]
It seems that Matlab R2017a's internal functions are detected as a toolbox by toggleToolbox, and so `toggleToolbox all off` makes Matlab unusable:

https://gist.github.com/anonymous/54d7ea84905b0286f7e8b60cb8ba436c

**Comment by rodyo** [comment]
Yup. Silly mistake; that command also removed the "MATLAB" toolbox from the path, rendering all vanilla-MATLAB commands invalid. 
Latest commit fixes this issue. Thanks for reporting the issue!
