### ISSUE TITLE
Just use getpref/setpref? (instead of matfile)

### ISSUE THREAD

**Issue by rodyo** [rodyo/FEX-toggleToolbox#3]
As suggested by [Rik Wisselink](https://www.mathworks.com/matlabcentral/profile/authors/3073010-rik-wisselink?s_tid=mlc_ans_email_prof)

**Comment by thrynae** [comment]
I have already made the required edits for my personal use (see the field names below). Would you like me to create a pull request?
`setpref('RodyOldenhuis',...%author name as group ID`\
`                ['toggleToolbox___',...%function group`\
`                'toolbox_states'],...%preference name`\
`                toolbox_states);`

**Comment by rodyo** [comment]
Yes please :)
